language: c
compiler:
  - clang
  - gcc
addons:
    apt:
        packages:
            - lcov

script:
  - cmake . -DCMAKE_BUILD_TYPE=Debug
  - make
  - make test
after_success:
  - make coverage
  - bash <(curl -s https://codecov.io/bash)
